'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Download,FileText,Check} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {catalog} from '../products/catalog';
export function QuoteForm(){
 const [product,setProduct]=useState(''),[draft,setDraft]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('product');if(id&&catalog.some(item=>item.id===id))setProduct(id)},[]);
 const prepare=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const item=catalog.find(item=>item.id===product);setDraft(['CONCORD — ENQUIRY DRAFT','Not sent. Sample product information; specifications require confirmation.','',`Name: ${data.get('name')}`,`Email: ${data.get('email')}`,`Company: ${data.get('company')||'—'}`,`Location: ${data.get('location')}`,`Product: ${item?.name??'General enquiry'}`,`Example pack size: ${item?.format??'—'}`,`Quantity (packs / units): ${data.get('quantity')}`,'',`Message: ${data.get('message')||'Please provide product information and a quotation.'}`].join('\n'));setSaved(false)};
 const download=()=>{const url=URL.createObjectURL(new Blob([draft],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='concord-enquiry-draft.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setSaved(true)};
 return <section className="quote-layout" id="quote"><div className="quote-intro"><p className="eyebrow">Let's find the right fit</p><h2>Start a conversation<br/>about your needs.</h2><p>Select a product and tell us what you need. Prepare an enquiry you can review and save.</p><div className="quote-disclosure"><FileText size={21}/><p>This form creates a draft on your device. It does not send your details. Direct submission will be available when contact details are connected.</p></div></div><div className="quote-panel"><form onSubmit={prepare} onChange={()=>{setDraft('');setSaved(false)}}><div className="form-two"><label>Your name <Input name="name" autoComplete="name" required maxLength={100}/></label><label>Email <Input name="email" type="email" autoComplete="email" required maxLength={200}/></label></div><div className="form-two"><label>Company <span className="optional">(optional)</span><Input name="company" autoComplete="organization" maxLength={150}/></label><label>City / country <Input name="location" required maxLength={150}/></label></div><label>Product <NativeSelect value={product} onChange={event=>setProduct(event.target.value)}><NativeSelectOption value="">General enquiry</NativeSelectOption>{catalog.map(item=><NativeSelectOption key={item.id} value={item.id}>{item.name} · {item.format}</NativeSelectOption>)}</NativeSelect></label><label>Quantity <span className="optional">(packs / units)</span><Input name="quantity" type="number" min="1" step="1" required placeholder="e.g. 100"/></label><label>Message <span className="optional">(optional)</span><Textarea name="message" rows={4} maxLength={2000} placeholder="Tell us about your intended use, delivery needs or questions."/></label><button className="pill" type="submit">Prepare enquiry <ArrowRight size={20}/></button></form>{draft&&<div className="quote-result" role="status"><h3>Your draft is ready</h3><p>Review it below. Nothing has been sent.</p><pre>{draft}</pre><button className="pill" onClick={download}>{saved?<Check size={18}/>:<Download size={18}/>} {saved?'Download again':'Download draft'}</button></div>}</div></section>
}
