'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ChevronLeft,ChevronRight,ShieldCheck,Settings,Users} from 'lucide-react';
import {Crop} from '@/components/site/crop';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const products=[['Wet Wipes','Gentle care\nfor everyday use.',68,647],['Wet Towel','Practical freshness\nanywhere.',518,647],['Animal Care Wipes','Trusted for your\ncompanions.',68,770],['WC Blocks','Freshness and\nhygiene for every visit.',518,770],['MOP Compatible Towels','Effective cleaning.\nLess effort.',68,894],['MOP','Designed for\neveryday cleaning.',518,894]] as const;
const heroSlides=[{x:470,y:260,w:554,h:290,alt:'Concord wet wipes'},...products.map(p=>({x:p[2],y:p[3],w:201,h:114,alt:p[0]}))];
function HeroCarousel(){const [slide,setSlide]=useState(0);const [hovered,setHovered]=useState(false);const [focused,setFocused]=useState(false);useEffect(()=>{if(hovered||focused)return;const timer=window.setInterval(()=>setSlide(current=>(current+1)%heroSlides.length),8000);return ()=>window.clearInterval(timer)},[slide,hovered,focused]);const move=(direction:number)=>setSlide(current=>(current+direction+heroSlides.length)%heroSlides.length);return <div className="hero-gallery" role="region" aria-roledescription="carousel" aria-label="Concord product images" onMouseEnter={()=>setHovered(true)} onMouseLeave={()=>setHovered(false)} onFocusCapture={()=>setFocused(true)} onBlurCapture={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setFocused(false)}} onKeyDown={event=>{if(event.key==='ArrowLeft'){event.preventDefault();move(-1)}if(event.key==='ArrowRight'){event.preventDefault();move(1)}}}><div className="hero-photo" key={slide}><Crop {...heroSlides[slide]}/></div><button className="hero-prev" aria-label="Previous product image" onClick={()=>move(-1)}><ChevronLeft/></button><button className="hero-next" aria-label="Next product image" onClick={()=>move(1)}><ChevronRight/></button><div className="hero-gallery-controls"><span aria-live={hovered||focused?'polite':'off'}>{slide+1} / {heroSlides.length}</span></div></div>}
export default function Home(){const [modal,setModal]=useState<{title:string;body:string;product?:number}|null>(null);return <main id="top">

<section className="hero"><HeroCarousel/><div className="hero-inner"><p className="eyebrow">Hygiene for everyday life</p><h1>Trusted<br/>Hygiene Solutions<br/><span>for Every Moment</span></h1><p className="hero-copy">At Concord, we develop high-quality hygiene products that bring comfort, care and freshness to everyday life — for homes, workplaces and beyond.</p><div className="hero-buttons"><a className="pill" href="/products">Explore Our Products <ArrowRight size={20}/></a></div></div></section>
<section className="products section" id="products"><div className="section-heading"><div><h2>Our Product Range</h2><p>Practical hygiene solutions designed for every need.</p></div></div><div className="product-wrap"><div className="product-grid" id="product-grid">{products.map((p,index)=>{return <button className="product" key={p[0]} onClick={()=>setModal({title:p[0],body:p[1].replace('\n',' ')+' Discover practical hygiene essentials for the spaces and moments that matter. Contact the Concord team for product specifications and availability.',product:index})}><Crop x={p[2]} y={p[3]} w={201} h={114} alt={p[0]}/><div className="product-copy"><h3>{p[0]}</h3><p>{p[1]}</p></div><span className="round-arrow"><ArrowRight size={20}/></span></button>})}</div></div></section>
<section className="about section" id="about"><div className="about-copy"><h2>About Concord</h2><p>We are a hygiene company driven by a simple belief: everyday care makes a big difference. With a focus on quality, innovation and reliability, we create products that support healthier and more comfortable lives at home, at work and for the ones you care for.</p><a className="pill" href="/about">Learn More About Concord <ArrowRight size={20}/></a></div><Crop x={423} y={1057} w={300} h={235} className="about-image" alt="A water droplet on soft white hygiene fabric"/><div className="values"><div className="value"><span className="value-icon"><ShieldCheck/></span><div><h3>Trusted Quality</h3><p>Reliable products<br/>you can count on.</p></div></div><div className="value"><span className="value-icon"><Settings/></span><div><h3>Practical Care</h3><p>Solutions for real<br/>life needs.</p></div></div><div className="value"><span className="value-icon"><Users/></span><div><h3>For Every Space</h3><p>Home, workplace<br/>and beyond.</p></div></div></div></section>
<Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className="detail-dialog">{modal?.product!==undefined&&<Crop x={products[modal.product][2]} y={products[modal.product][3]} w={201} h={114} className="detail-image" alt={modal.title}/>}<DialogTitle className="detail-title">{modal?.title}</DialogTitle><DialogDescription className="detail-description">{modal?.body}</DialogDescription></DialogContent></Dialog>
</main>}
