import type {Metadata} from 'next';
import {Text} from '@/components/site/language';
import {ArrowRight,ShieldCheck,Settings,Users} from 'lucide-react';
import {Crop} from '@/components/site/crop';
export const metadata:Metadata={title:'About Concord — Everyday Care',description:'Learn about Concord and our approach to everyday hygiene.'};
export default function AboutPage(){return <main className="interior-page company-about"><section className="interior-heading"><a className="breadcrumb" href="/"><Text value={"Home / About"}/></a><p className="eyebrow"><Text value={"About Concord"}/></p><h1><Text value={"25 years of experience,"}/><br/><span><Text value={"with the care of day one."}/></span></h1><Crop x={423} y={1057} w={300} h={235} className="company-intro-image" alt="A water droplet on soft white hygiene fabric"/></section><section className="company-story"><p><Text value="Atlas Itriyat ve Temizlik; sektörde yarım asırdır faaliyet gösteren TNCR Gıda ve Temizlik Ürünleri Dağıtım Sanayi ve Ticaret Limited Şirketi'nin yan kuruluşudur."/></p><p><Text value="TNCR Gıda olarak, 20 yılı aşkın sektör tecrübemizle toptan ve perakende alanında güvenin adresi olmaya devam ediyoruz. Temizlik, kozmetik ve hijyen grubu ürünlerinde, gelişen teknolojiyi ve değişen tüketici ihtiyaçlarını yakından takip ediyor; en yeni ürünleri en ulaşılabilir koşullarda iş ortaklarımızla buluşturuyoruz."/></p><p><Text value="Müşteri memnuniyetini işimizin merkezine alarak, gelen taleplere hızlı, etkili ve profesyonel çözümler sunuyoruz. Hedefimiz; kalite ve güven ilkelerimizden taviz vermeden, sektörün lider kuruluşları arasındaki yerimizi daha da sağlamlaştırmaktır."/></p></section><section className="about-principles" aria-label="Our values"><article><ShieldCheck/><h2><Text value={"Trusted Quality"}/></h2><p><Text value={"Reliable products you can count on for everyday care."}/></p></article><article><Settings/><h2><Text value={"Practical Care"}/></h2><p><Text value={"Simple solutions for the hygiene needs of everyday life."}/></p></article><article><Users/><h2><Text value={"For Every Space"}/></h2><p><Text value={"Care for your home, your workplace and beyond."}/></p></article></section></main>}



