'use client';
import {Text} from '@/components/site/language';
import {useState} from 'react';
import {ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {categories,catalog} from './catalog';
export function ProductCatalog(){const [selected,setSelected]=useState<(typeof catalog)[number]|null>(null);return <><nav className="category-links" aria-label="Product categories">{categories.map((category,index)=><a key={category} href={`#category-${index}`}><Text value={category}/></a>)}</nav>{categories.map((category,index)=><section className="catalog-category" id={`category-${index}`} key={category}><div className="catalog-category-heading"><h2><Text value={category}/></h2><span>{catalog.filter(item=>item.category===category).length} <Text value="products"/></span></div><div className="catalog-grid">{catalog.filter(item=>item.category===category).map(item=><button className="catalog-card" id={item.id} key={item.id} onClick={()=>setSelected(item)}><div className="catalog-product-photo"><img src={item.image} alt={item.name} loading="lazy"/></div><div className="catalog-card-copy"><h3><Text value={item.name}/></h3><p><Text value={item.format}/></p><span className="catalog-card-action"><Text value={"Product details "}/><ArrowRight size={20}/></span></div></button>)}</div></section>)}<Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="detail-dialog">{selected&&<div className="catalog-product-photo"><img src={selected.image} alt={selected.name}/></div>}<DialogTitle className="detail-title"><Text value={selected?.name}/></DialogTitle><DialogDescription className="detail-description"><Text value={selected?.description}/></DialogDescription><dl className="product-specs"><div><dt><Text value={"Category"}/></dt><dd><Text value={selected?.category}/></dd></div><div><dt><Text value={"Pack size"}/></dt><dd><Text value={selected?.format}/></dd></div></dl><a className="pill" href="/contact"><Text value={"Enquire about this product "}/><ArrowRight size={20}/></a></DialogContent></Dialog></>}


